require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ArtisansController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Artisan. As you add validations to Artisan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArtisansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all artisans as @artisans" do
      artisan = Artisan.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:artisans)).to eq([artisan])
    end
  end

  describe "GET #show" do
    it "assigns the requested artisan as @artisan" do
      artisan = Artisan.create! valid_attributes
      get :show, {:id => artisan.to_param}, valid_session
      expect(assigns(:artisan)).to eq(artisan)
    end
  end

  describe "GET #new" do
    it "assigns a new artisan as @artisan" do
      get :new, {}, valid_session
      expect(assigns(:artisan)).to be_a_new(Artisan)
    end
  end

  describe "GET #edit" do
    it "assigns the requested artisan as @artisan" do
      artisan = Artisan.create! valid_attributes
      get :edit, {:id => artisan.to_param}, valid_session
      expect(assigns(:artisan)).to eq(artisan)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Artisan" do
        expect {
          post :create, {:artisan => valid_attributes}, valid_session
        }.to change(Artisan, :count).by(1)
      end

      it "assigns a newly created artisan as @artisan" do
        post :create, {:artisan => valid_attributes}, valid_session
        expect(assigns(:artisan)).to be_a(Artisan)
        expect(assigns(:artisan)).to be_persisted
      end

      it "redirects to the created artisan" do
        post :create, {:artisan => valid_attributes}, valid_session
        expect(response).to redirect_to(Artisan.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved artisan as @artisan" do
        post :create, {:artisan => invalid_attributes}, valid_session
        expect(assigns(:artisan)).to be_a_new(Artisan)
      end

      it "re-renders the 'new' template" do
        post :create, {:artisan => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested artisan" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => new_attributes}, valid_session
        artisan.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested artisan as @artisan" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => valid_attributes}, valid_session
        expect(assigns(:artisan)).to eq(artisan)
      end

      it "redirects to the artisan" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => valid_attributes}, valid_session
        expect(response).to redirect_to(artisan)
      end
    end

    context "with invalid params" do
      it "assigns the artisan as @artisan" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => invalid_attributes}, valid_session
        expect(assigns(:artisan)).to eq(artisan)
      end

      it "re-renders the 'edit' template" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested artisan" do
      artisan = Artisan.create! valid_attributes
      expect {
        delete :destroy, {:id => artisan.to_param}, valid_session
      }.to change(Artisan, :count).by(-1)
    end

    it "redirects to the artisans list" do
      artisan = Artisan.create! valid_attributes
      delete :destroy, {:id => artisan.to_param}, valid_session
      expect(response).to redirect_to(artisans_url)
    end
  end

end
