require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StoreUsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StoreUser. As you add validations to StoreUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StoreUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all store_users as @store_users" do
      store_user = StoreUser.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:store_users)).to eq([store_user])
    end
  end

  describe "GET #show" do
    it "assigns the requested store_user as @store_user" do
      store_user = StoreUser.create! valid_attributes
      get :show, {:id => store_user.to_param}, valid_session
      expect(assigns(:store_user)).to eq(store_user)
    end
  end

  describe "GET #new" do
    it "assigns a new store_user as @store_user" do
      get :new, {}, valid_session
      expect(assigns(:store_user)).to be_a_new(StoreUser)
    end
  end

  describe "GET #edit" do
    it "assigns the requested store_user as @store_user" do
      store_user = StoreUser.create! valid_attributes
      get :edit, {:id => store_user.to_param}, valid_session
      expect(assigns(:store_user)).to eq(store_user)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StoreUser" do
        expect {
          post :create, {:store_user => valid_attributes}, valid_session
        }.to change(StoreUser, :count).by(1)
      end

      it "assigns a newly created store_user as @store_user" do
        post :create, {:store_user => valid_attributes}, valid_session
        expect(assigns(:store_user)).to be_a(StoreUser)
        expect(assigns(:store_user)).to be_persisted
      end

      it "redirects to the created store_user" do
        post :create, {:store_user => valid_attributes}, valid_session
        expect(response).to redirect_to(StoreUser.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved store_user as @store_user" do
        post :create, {:store_user => invalid_attributes}, valid_session
        expect(assigns(:store_user)).to be_a_new(StoreUser)
      end

      it "re-renders the 'new' template" do
        post :create, {:store_user => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested store_user" do
        store_user = StoreUser.create! valid_attributes
        put :update, {:id => store_user.to_param, :store_user => new_attributes}, valid_session
        store_user.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested store_user as @store_user" do
        store_user = StoreUser.create! valid_attributes
        put :update, {:id => store_user.to_param, :store_user => valid_attributes}, valid_session
        expect(assigns(:store_user)).to eq(store_user)
      end

      it "redirects to the store_user" do
        store_user = StoreUser.create! valid_attributes
        put :update, {:id => store_user.to_param, :store_user => valid_attributes}, valid_session
        expect(response).to redirect_to(store_user)
      end
    end

    context "with invalid params" do
      it "assigns the store_user as @store_user" do
        store_user = StoreUser.create! valid_attributes
        put :update, {:id => store_user.to_param, :store_user => invalid_attributes}, valid_session
        expect(assigns(:store_user)).to eq(store_user)
      end

      it "re-renders the 'edit' template" do
        store_user = StoreUser.create! valid_attributes
        put :update, {:id => store_user.to_param, :store_user => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested store_user" do
      store_user = StoreUser.create! valid_attributes
      expect {
        delete :destroy, {:id => store_user.to_param}, valid_session
      }.to change(StoreUser, :count).by(-1)
    end

    it "redirects to the store_users list" do
      store_user = StoreUser.create! valid_attributes
      delete :destroy, {:id => store_user.to_param}, valid_session
      expect(response).to redirect_to(store_users_url)
    end
  end

end
